name:    audiobook-podcast
version: "0.0.0"

dependencies:
- aeson
- base
- classy-prelude-yesod 
- filepath
- shakespeare
- warp
- template-haskell
- wai
- wai-extra
- monad-logger
- wai-logger
- fast-logger
- yesod-static
- yesod-core
- yesod
- beam-core
- beam-sqlite
- sqlite-simple
- text
- mime-types
- transformers
- directory
- zip
- natural-sort
- containers
- bytestring
- conduit
- conduit-extra
- binary
- exceptions
- temporary
- process
- http-types
- yesod-newsfeed
- time
- scientific
- case-insensitive
- stm
- async
- mtl
- safe-exceptions
- process-extras
- attoparsec
- mono-traversable

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  default-extensions: NamedFieldPuns, OverloadedStrings
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
        - -Wall
        - -fwarn-tabs
        - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -Wcompat 
      - -Wincomplete-record-updates 
      - -Wincomplete-uni-patterns 
      - -Wredundant-constraints
      - -O2

# Runnable executable for our application
executables:
  audiobook-podcast:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - audiobook-podcast
    when:
    - condition: flag(library-only)
      buildable: false

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
