name:                calibre-audiobook
version:             0.1.0.0
github:              "felixscheinost/calibre-audiobook"
license:             MIT
author:              "Felix Scheinost"
maintainer:          "felix.scheinost@posteo.de"
copyright:           "2018 Felix Scheinost"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/felixscheinost/calibre-audiobook#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- process
- aeson
- bytestring

library:
  source-dirs: src

executables:
  calibre-audiobook-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calibre-audiobook


tests:
  calibre-audiobook-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - test
