BookView: Alle Hörbücher
SeriesView: Nach Reihe
BookNeedConvertView: Benötigen Konvertierung
ConversionsView: Konvertierungen
SettingsView: Einstellungen
NavBookCategory: Hörbücher

Search: Suchen
Cancel: Abbrechen
Convert: Konvertieren

ConversionRunning: Laufend
ConversionQueued: Warteschlange
ConversionFinished: Abgeschlossen

NoAudioFilesInZip: ZIP enthält keine unterstützten Audio-Dateien
ZipContainsMultipleFormats: ZIP enthält Audio-Dateien mit unterschiedlichen Formaten
BookAlreadyContainsTargetFormat: Buch hat das Format schon

CopyRSSLink: Podcast-Link kopieren
DownloadMP3: MP3 herunterladen

SelectBooks: Auswählen