BookView: All audiobooks
SeriesView: By series
BookNeedConvertView:Need conversion
ConversionsView: Conversions
NavBookCategory: Audiobooks

Search: Search
Cancel: Cancel
Convert: Convert

ConversionRunning: Running
ConversionQueued: Queued
ConversionFinished: Finished

NoAudioFilesInZip: ZIP doesn't contain any supported audio files
ZipContainsMultipleFormats: ZIP contains files with different audio format
BookAlreadyContainsTargetFormat: Book already has that format

CopyRSSLink: Copy link to podcast
DownloadMP3: Download MP3

SelectBooks: Select
